# Adaptive Enemy AI Mod Info
# Ducky SDK uses this file for mod metadata.

name=AdaptiveEnemyAI
displayName=Adaptive Enemy AI(v1.4.0)
description=Enemy AI adapts its tactics based on player loadout and behavior.

version=1.4.0
author=inggom
tags=Gameplay,AI,Enemy
publishedFileId=3661223437
