# Adaptive Enemy AI Mod Info
# Ducky SDK uses this file for mod metadata.

name=AdaptiveEnemyAI
displayName=Adaptive Enemy AI(v1.3.9)
description=Enemy AI adapts its tactics based on player loadout and behavior.

version=1.3.9
author=inggom
tags=Gameplay,AI,Enemy
publishedFileId=3661223437
